export const ERROR_CODES = {
	VALIDATION_ERROR: 'VALIDATION_ERROR',
	AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
	AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
	NOT_FOUND: 'NOT_FOUND',
	CONFLICT: 'CONFLICT',
	RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
	INTERNAL_ERROR: 'INTERNAL_ERROR',
	USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
	WEAK_PASSWORD: 'WEAK_PASSWORD',
	INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
	EMAIL_PROVIDER_DISABLED: 'EMAIL_PROVIDER_DISABLED',
	EMAIL_RATE_LIMIT_EXCEEDED: 'EMAIL_RATE_LIMIT_EXCEEDED',
	EMAIL_NOT_CONFIRMED: 'EMAIL_NOT_CONFIRMED',
	PHONE_NOT_CONFIRMED: 'PHONE_NOT_CONFIRMED',
	USER_NOT_FOUND: 'USER_NOT_FOUND',
	SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
	SESSION_EXPIRED: 'SESSION_EXPIRED',
	REFRESH_TOKEN_NOT_FOUND: 'REFRESH_TOKEN_NOT_FOUND',
	REFRESH_TOKEN_ALREADY_USED: 'REFRESH_TOKEN_ALREADY_USED',
	OTP_EXPIRED: 'OTP_EXPIRED',
	OTP_DISABLED: 'OTP_DISABLED',
	CAPTCHA_FAILED: 'CAPTCHA_FAILED',
	ANONYMOUS_PROVIDER_DISABLED: 'ANONYMOUS_PROVIDER_DISABLED',
	PHONE_PROVIDER_DISABLED: 'PHONE_PROVIDER_DISABLED',
	PROVIDER_DISABLED: 'PROVIDER_DISABLED',
	SIGNUP_DISABLED: 'SIGNUP_DISABLED',
	USER_BANNED: 'USER_BANNED',
	REAUTHENTICATION_NEEDED: 'REAUTHENTICATION_NEEDED',
	SAME_PASSWORD: 'SAME_PASSWORD',
	TRANSPORT_ERROR_TRANSIENT: 'TRANSPORT_ERROR_TRANSIENT',
	TRANSPORT_ERROR_PERMANENT: 'TRANSPORT_ERROR_PERMANENT',
	TEMPLATE_ERROR: 'TEMPLATE_ERROR',
	GUARDRAIL_VIOLATION: 'GUARDRAIL_VIOLATION',
	USAGE_LIMIT_EXCEEDED: 'USAGE_LIMIT_EXCEEDED',
	UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;

export const ERROR_MESSAGES: Record<ErrorCode, string> = {
	USER_ALREADY_EXISTS: 'User with this email already exists',
	WEAK_PASSWORD: 'Password is too weak',
	EMAIL_PROVIDER_DISABLED: 'Email registration is disabled',
	EMAIL_RATE_LIMIT_EXCEEDED: 'Too many emails sent. Please try again later',
	INVALID_CREDENTIALS: 'Invalid email or password',
	CONFLICT: 'Resource conflict',
	VALIDATION_ERROR: 'Validation failed',
	RATE_LIMIT_EXCEEDED: 'Too many requests. Please try again later',
	AUTHENTICATION_ERROR: 'Authentication failed',
	AUTHORIZATION_ERROR: 'Access denied',
	NOT_FOUND: 'Resource not found',
	INTERNAL_ERROR: 'Internal server error',
	EMAIL_NOT_CONFIRMED: 'Email address is not confirmed',
	PHONE_NOT_CONFIRMED: 'Phone number is not confirmed',
	USER_NOT_FOUND: 'User not found',
	SESSION_NOT_FOUND: 'Session not found',
	SESSION_EXPIRED: 'Session has expired',
	REFRESH_TOKEN_NOT_FOUND: 'Refresh token not found',
	REFRESH_TOKEN_ALREADY_USED: 'Refresh token has already been used',
	OTP_EXPIRED: 'OTP code has expired',
	OTP_DISABLED: 'OTP login is disabled',
	CAPTCHA_FAILED: 'CAPTCHA verification failed',
	ANONYMOUS_PROVIDER_DISABLED: 'Anonymous sign-in is disabled',
	PHONE_PROVIDER_DISABLED: 'Phone authentication is disabled',
	PROVIDER_DISABLED: 'This authentication provider is disabled',
	SIGNUP_DISABLED: 'Sign-ups are disabled',
	USER_BANNED: 'User account has been banned',
	REAUTHENTICATION_NEEDED: 'Please reauthenticate to continue',
	SAME_PASSWORD: 'New password must be different from current password',
	TRANSPORT_ERROR_TRANSIENT: 'Transient transport error',
	TRANSPORT_ERROR_PERMANENT: 'Permanent transport error',
	TEMPLATE_ERROR: 'Template error',
	GUARDRAIL_VIOLATION: 'Guardrail violation',
	USAGE_LIMIT_EXCEEDED: 'Usage limit exceeded',
	UNKNOWN_ERROR: 'Unknown error',
};

export const ERROR_MESSAGES_PL: Record<ErrorCode, string> = {
	USER_ALREADY_EXISTS: 'Użytkownik z tym adresem email już istnieje',
	WEAK_PASSWORD: 'Hasło jest zbyt słabe',
	EMAIL_PROVIDER_DISABLED: 'Rejestracja przez email jest wyłączona',
	EMAIL_RATE_LIMIT_EXCEEDED:
		'Wysłano zbyt wiele wiadomości. Spróbuj ponownie później',
	INVALID_CREDENTIALS: 'Nieprawidłowy email lub hasło',
	CONFLICT: 'Konflikt zasobów',
	VALIDATION_ERROR: 'Walidacja nie powiodła się',
	RATE_LIMIT_EXCEEDED: 'Zbyt wiele prób. Spróbuj ponownie później',
	AUTHENTICATION_ERROR: 'Błąd uwierzytelniania',
	AUTHORIZATION_ERROR: 'Brak dostępu',
	NOT_FOUND: 'Zasób nie został znaleziony',
	INTERNAL_ERROR: 'Wewnętrzny błąd serwera',
	EMAIL_NOT_CONFIRMED: 'Adres email nie został potwierdzony',
	PHONE_NOT_CONFIRMED: 'Numer telefonu nie został potwierdzony',
	USER_NOT_FOUND: 'Użytkownik nie został znaleziony',
	SESSION_NOT_FOUND: 'Sesja nie została znaleziona',
	SESSION_EXPIRED: 'Sesja wygasła',
	REFRESH_TOKEN_NOT_FOUND: 'Token odświeżania nie został znaleziony',
	REFRESH_TOKEN_ALREADY_USED: 'Token odświeżania został już użyty',
	OTP_EXPIRED: 'Kod OTP wygasł',
	OTP_DISABLED: 'Logowanie przez OTP jest wyłączone',
	CAPTCHA_FAILED: 'Weryfikacja CAPTCHA nie powiodła się',
	ANONYMOUS_PROVIDER_DISABLED: 'Logowanie anonimowe jest wyłączone',
	PHONE_PROVIDER_DISABLED: 'Uwierzytelnianie przez telefon jest wyłączone',
	PROVIDER_DISABLED: 'Ten dostawca uwierzytelniania jest wyłączony',
	SIGNUP_DISABLED: 'Rejestracja jest wyłączona',
	USER_BANNED: 'Konto użytkownika zostało zablokowane',
	REAUTHENTICATION_NEEDED: 'Wymagane ponowne uwierzytelnienie',
	SAME_PASSWORD: 'Nowe hasło musi być różne od obecnego',
	TRANSPORT_ERROR_TRANSIENT: 'Transient transport error',
	TRANSPORT_ERROR_PERMANENT: 'Permanent transport error',
	TEMPLATE_ERROR: 'Błąd szablonu',
	GUARDRAIL_VIOLATION: 'Naruszenie guardrail',
	USAGE_LIMIT_EXCEEDED: 'Przekroczono limit użycia',
	UNKNOWN_ERROR: 'Nieznany błąd',
};
